import { Geist, Geist_Mono } from "next/font/google";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/context/ToastContext";
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
});



export default function RootLayout({ children }) {
  return (

    <html
      suppressHydrationWarning={true}
      lang="en"
      className={`h-full antialiased ${jakarta.className}`
      }
    >

      <body suppressHydrationWarning={true} className="min-h-full flex flex-col ">
        <AuthProvider>  
          <ToastProvider>
          {children}
        </ToastProvider>
        </AuthProvider>
      </body>
    </html >
  );
}
